#! /bin/bash
sudo docker stop productService
sudo docker rm productService
sudo docker rmi lw5-productserv
sudo docker stop inventoryService
sudo docker rm inventoryService
sudo docker rmi lw5-inventoryserv
sudo docker stop notificationService
sudo docker rm notificationService
sudo docker rmi lw5-notificationserv
sudo docker stop shopBDserver
sudo docker rm shopBDserver
sudo docker rmi lw5-shopbd
sudo docker stop rmqServer
sudo docker rm rmqServer
sudo docker stop keyDBserver
sudo docker rm keyDBserver
sudo docker compose up